# Generated by Django 4.1.2 on 2023-06-02 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='category_title')),
                ('slug', models.SlugField(max_length=55, verbose_name='category_slug')),
                ('description', models.TextField(blank=True, verbose_name='category_description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='category_image')),
                ('is_active', models.BooleanField(verbose_name='is_active')),
                ('is_featured', models.BooleanField(verbose_name='is_featured')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='products_title')),
                ('slug', models.SlugField(max_length=55, verbose_name='products_slug')),
                ('description', models.TextField(blank=True, verbose_name='product_description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='products_image')),
                ('gamelink', models.TextField(blank=True, verbose_name='game_link')),
                ('is_active', models.BooleanField(verbose_name='is_active')),
                ('is_featured', models.BooleanField(verbose_name='is_featured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigamesapp.category', verbose_name='product_category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigamesapp.products', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
